@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhdHJpY2suc21pdGhAY29kZXJhY2FkZW15LmVkdS5hdSIsImlhdCI6MTUxNTg1MDI1MywiZXhwIjoxNTE2NDU1MDUzLCJzdWIiOiI1YTI3NzYyMzhmZjE3ODA1MDRiMWQxOTAifQ.9vAto6y4DTXMtTvPfqPbnXPr02wbBiBZ3Bn7t7CLrFs

### Sign in
POST http://localhost:7000/auth
Content-Type: application/json

{
  "email": "patrick.smith@coderacademy.edu.au",
  "password": "password123"
}

### Get Products
GET http://localhost:7000/products
Authorization: Bearer {{ token }}

### Get Sales
GET http://localhost:7000/sales
Authorization: Bearer {{ token }}

### Register
POST http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "patrick.smith@coderacademy.edu.au",
  "firstName": "Patrick",
  "lastName": "Smith",
  "password": "password123"
}

### Create product
POST http://localhost:7000/products
Authorization: Bearer {{ token }}
Content-Type: application/json

{
  "category": "Wa-Bocho",
  "code": "41107",
  "title": "240mm Yanagiba Aoniko Hongasumi with saya",
  "price": 100,
  "totalSales": 32
}
### Create Sale
POST http://localhost:7000/sales
Authorization: Bearer {{ token }}
Content-Type: application/json

{
  "products": [""]
}

### Edit Sale
PUT http://localhost:7000/sale/5a5a08e62a428f2e2449b9eb
Authorization: Bearer {{ token }}
Content-Type: application/json

{
   "products": [
        "5a54af5f8edb60461c4f45e4"
    ]
}

### Update product
PUT http://localhost:7000/product/5a54e6dce51e644448cd7811
Authorization: Bearer {{ token }}
Content-Type: application/json

{
  "code": "41109"
}

### Delete product
DELETE http://localhost:7000/product/5a54e6dce51e644448cd7811
Authorization: Bearer {{ token }}
Content-Type: application/json


### Read customer
GET http://localhost:7000/customers
Authorization: Bearer {{ token }}

### Add to customer
POST http://localhost:7000/customers
Authorization: Bearer {{ token }}

{
   "gender": "Male",
   "phone": "0433001122",
   "email": "patrick.smith@coderacademy.edu.au",
   "firstName": "Taro",
   "lastName": "Yamada",
   "isChef": 1
}


### Update customer
PUT http://localhost:7000/customer/5a555f3ae51e644448cd7812
Authorization: Bearer {{ token }}
Content-Type: application/json

{
   "firstName": "Emma",
   "lastName": "",
   "gender": "female",
   "purchasedHistory": [],
   "isChef": false,
   "workAt": "Kmart",
   "origin": "SNS (Facebook, Twitter etc)",
   "note": "Long text Long text Long text Long text Long text Long text Long text Long text "   
}

