@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhdHJpY2suc21pdGhAY29kZXJhY2FkZW15LmVkdS5hdSIsImlhdCI6MTUxNTUwNzIxMiwiZXhwIjoxNTE2MTEyMDEyLCJzdWIiOiI1YTI3NzYyMzhmZjE3ODA1MDRiMWQxOTAifQ.i2sZmnYKUMlnaMgUL9-tbCAb_lKOkeJ_KdbyweISmCU

GET http://localhost:7000/products
Authorization: Bearer {{ token }}

### Register
POST http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "patrick.smith@coderacademy.edu.au",
  "firstName": "Patrick",
  "lastName": "Smith",
  "password": "password123"
}

### Sign in
POST http://localhost:7000/auth
Content-Type: application/json

{
  "email": "chymeng24@gmail.com",
  "password": "123456"
}

### Create product
POST http://localhost:7000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoeW1lbmcyNEBnbWFpbC5jb20iLCJpYXQiOjE1MTU3MzY4NzcsImV4cCI6MTUxNjM0MTY3Nywic3ViIjoiNWE1MmY3OWMyZmMzNTA4YzZlZTBiZjEzIn0.VgJYyj33b9ajFfCzLQXaA7Mkml3cPnaP-bnXhSiBJkk
Content-Type: application/json

{
  "category": "Wa-Boch`o",
  "code": "41103",
  "title": "240mm Yanagiba Aoniko Hongasumi with saya",
  "price": 100,
  "totalSales": 32
}

### Update product
PUT http://localhost:7000/products/5a54afbe8edb60461c4f45e6
Authorization: Bearer {{ token }}
Content-Type: application/json

{
  "price": 85
}

### Delete product
DELETE http://localhost:7000/products/5a54adff8edb60461c4f45e3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhdHJpY2suc21pdGhAY29kZXJhY2FkZW15LmVkdS5hdSIsImlhdCI6MTUxNTQ5ODk4NCwiZXhwIjoxNTE2MTAzNzg0LCJzdWIiOiI1YTI3NzYyMzhmZjE3ODA1MDRiMWQxOTAifQ.vvyLNZDa4YYDxe5oMieNBm7WV2GyiKXzm8pwKPlClm4
Content-Type: application/json

{
  "category": "Wa-Bocho",
  "code": "41135",
  "title": "150mm Deba Aoniko Hongasumi with saya"
}

### Read customer
GET http://localhost:7000/customers
Authorization: Bearer {{ token }}

### Add to customer
POST http://localhost:7000/customers
Authorization: Bearer {{ token }}

{
   "firstName": "Tomomi",
   "lastName": "Oki",
   "gender": "Female",
   "phone": "0433001122",
   "email": "patrick.smith@coderacademy.edu.au",
   "isChef": 1
}


### Update customer
PUT http://localhost:7000/customers/5a555f3ae51e644448cd7812
Authorization: Bearer {{ token }}
Content-Type: application/json

{
   "purchasedHistory": [],
   "workAt": "Kmart",
   "origin": "SNS (Facebook, Twitter etc)",
   "note": "Japan OTAKU, traveling at least once a year to Japan, love JP knives too, have many JP knives",
   
}

